/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AnmeldenRouteImport } from './routes/anmelden'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppEinstellungenRouteImport } from './routes/_app/einstellungen'
import { Route as AppFaecherRouteImport } from './routes/_app/faecher'
import { Route as AppNotenRouteImport } from './routes/_app/noten'
import { Route as AppZeugnisRouteImport } from './routes/_app/zeugnis'
import { Route as ApiHealthzRouteImport } from './routes/api/healthz'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEinstellungenRoute = AppEinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => AppRoute,
} as any)
const AppFaecherRoute = AppFaecherRouteImport.update({
  id: '/faecher',
  path: '/faecher',
  getParentRoute: () => AppRoute,
} as any)
const AppNotenRoute = AppNotenRouteImport.update({
  id: '/noten',
  path: '/noten',
  getParentRoute: () => AppRoute,
} as any)
const AppZeugnisRoute = AppZeugnisRouteImport.update({
  id: '/zeugnis',
  path: '/zeugnis',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/einstellungen': typeof AppEinstellungenRoute
  '/faecher': typeof AppFaecherRoute
  '/noten': typeof AppNotenRoute
  '/zeugnis': typeof AppZeugnisRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/anmelden': typeof AnmeldenRoute
  '/einstellungen': typeof AppEinstellungenRoute
  '/faecher': typeof AppFaecherRoute
  '/noten': typeof AppNotenRoute
  '/zeugnis': typeof AppZeugnisRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/anmelden': typeof AnmeldenRoute
  '/_app/einstellungen': typeof AppEinstellungenRoute
  '/_app/faecher': typeof AppFaecherRoute
  '/_app/noten': typeof AppNotenRoute
  '/_app/zeugnis': typeof AppZeugnisRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anmelden'
    | '/einstellungen'
    | '/faecher'
    | '/noten'
    | '/zeugnis'
    | '/api/healthz'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/anmelden'
    | '/einstellungen'
    | '/faecher'
    | '/noten'
    | '/zeugnis'
    | '/api/healthz'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/anmelden'
    | '/_app/einstellungen'
    | '/_app/faecher'
    | '/_app/noten'
    | '/_app/zeugnis'
    | '/api/healthz'
    | '/_app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AnmeldenRoute: typeof AnmeldenRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/einstellungen': {
      id: '/_app/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AppEinstellungenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faecher': {
      id: '/_app/faecher'
      path: '/faecher'
      fullPath: '/faecher'
      preLoaderRoute: typeof AppFaecherRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/noten': {
      id: '/_app/noten'
      path: '/noten'
      fullPath: '/noten'
      preLoaderRoute: typeof AppNotenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/zeugnis': {
      id: '/_app/zeugnis'
      path: '/zeugnis'
      fullPath: '/zeugnis'
      preLoaderRoute: typeof AppZeugnisRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppEinstellungenRoute: typeof AppEinstellungenRoute
  AppFaecherRoute: typeof AppFaecherRoute
  AppNotenRoute: typeof AppNotenRoute
  AppZeugnisRoute: typeof AppZeugnisRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEinstellungenRoute: AppEinstellungenRoute,
  AppFaecherRoute: AppFaecherRoute,
  AppNotenRoute: AppNotenRoute,
  AppZeugnisRoute: AppZeugnisRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AnmeldenRoute: AnmeldenRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
