apps:
    web:
        DATABASE_URL: ENC[AES256_GCM,data:jyHECprXK2sC1KWXSGTF3Cm9cidNQjtc6Xx/nf+8cPYPukCjAEiuWa5ADCbMMREniJIo0ITWQCgFsLz3J+CmsfCHy0pId+8=,iv:YWbai8sGPEqUei4/mPxgKvjXNhM5eVk6x2YIH2Joo+0=,tag:TlwpUrzFixCTSXyo5LKOMQ==,type:str]
        BETTER_AUTH_SECRET: ENC[AES256_GCM,data:YbFE/AN98aBATBDyqJbZAeqmEV3jfW7ccdMF18rdbCbT/pnDAfo/Ap8EIqI8haI2oyCHovipzE1RYGdM3UlDOw==,iv:XelTtzxG5zayqMoyirQHUDW/z5xShu/NFQt3yXC+6QM=,tag:/6zTC++RQpMU2dn439W6VQ==,type:str]
        GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:jlpmhGQCpXKBMU3BcpzSDjANEdhPERATGN4dIlA+Z3mugE+lqLqOIg==,iv:d18fI/0pFfc4ozrb6zgOtnSv6WJf8UqNrhBNOzvMDik=,tag:2ut6ak8Ic95QsV9BI6wZjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVEExUlBqbHRERHlIeUc4
            ZFg4MFFlUVAyNEFaOHV0Y1F4bmtsaFFjUlJFCjhYbWZZaUFMaFJMK08yQTBnVjdm
            Q1d6d3ZBa21nWHZWK2NHYlQrUWUwOUUKLS0tIE1taUZtYmpvcTRjcVFJOUZ3WGNK
            QkNSU0xhSERpcjlYdTBtMWdzVi9SWG8KcNkVRFSplL5LA1GnllbdkozThNvo3V42
            wIZiP5DyeXpPdADn8dWkB7SFq1Jj7Ef61U9mRgstdd90qmZgy+Wv0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gxzu2f027zu227f4wyf4jh5sw0w495482qfzv5flmfyjvgzxm3ys8p9muz
    lastmodified: "2026-07-26T18:54:57Z"
    mac: ENC[AES256_GCM,data:T7aAWfp62uJT7Vfj+9rlFQOXfu00eicbc/Dzwap1NLoJyFSqyP9wCNQFnL2ri4qBVuKuTRLORcXooeBNkPd+ycijGp9efEf8hcL5R5KsJMHqirss0+iIENlUGRoFag0czEsQuLRXw0JJyaTqLsWCIiTcVfobmEFGh5sPAKM0tqE=,iv:qYYdPzvjkadoNjk1rZlhBGN9xmNRB1UHqr6UY0Xa8QM=,tag:YKfuFE8zKHL8yaxWVw1fRQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
