apps:
    web:
        DATABASE_URL: ENC[AES256_GCM,data:jyHECprXK2sC1KWXSGTF3Cm9cidNQjtc6Xx/nf+8cPYPukCjAEiuWa5ADCbMMREniJIo0ITWQCgFsLz3J+CmsfCHy0pId+8=,iv:YWbai8sGPEqUei4/mPxgKvjXNhM5eVk6x2YIH2Joo+0=,tag:TlwpUrzFixCTSXyo5LKOMQ==,type:str]
        BETTER_AUTH_SECRET: ENC[AES256_GCM,data:j246aDeBflgn8bwx3sojkV4F4AXgGNYHYJUP1B0rFrKmy8mPf7Xxd/lNZW4OdtCnJFhIiVLZ+vNeaAe03Jkbug==,iv:BcrgqwUayoIzmstldUWRyuf3Caq1m5a4Q63kEA0JXkM=,tag:vPc5zlqMstlNOD3bv0p7qQ==,type:str]
        GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:jlpmhGQCpXKBMU3BcpzSDjANEdhPERATGN4dIlA+Z3mugE+lqLqOIg==,iv:d18fI/0pFfc4ozrb6zgOtnSv6WJf8UqNrhBNOzvMDik=,tag:2ut6ak8Ic95QsV9BI6wZjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVEExUlBqbHRERHlIeUc4
            ZFg4MFFlUVAyNEFaOHV0Y1F4bmtsaFFjUlJFCjhYbWZZaUFMaFJMK08yQTBnVjdm
            Q1d6d3ZBa21nWHZWK2NHYlQrUWUwOUUKLS0tIE1taUZtYmpvcTRjcVFJOUZ3WGNK
            QkNSU0xhSERpcjlYdTBtMWdzVi9SWG8KcNkVRFSplL5LA1GnllbdkozThNvo3V42
            wIZiP5DyeXpPdADn8dWkB7SFq1Jj7Ef61U9mRgstdd90qmZgy+Wv0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gxzu2f027zu227f4wyf4jh5sw0w495482qfzv5flmfyjvgzxm3ys8p9muz
    lastmodified: "2026-07-22T19:14:17Z"
    mac: ENC[AES256_GCM,data:1tIB0t3tpEF+KXp6m7FJuAqMspD+q1v5fj7G1bD45atSbgazT1I4rwwMAprxeLd1y0d9Vba8ERqF04r0ZqbXvIZ2E7dV/nWqXyiL+ItemY6mESOa/hDgoFxF33fWrQxiuc9RS2VvqUiyCpJ1V987bcJhSz/+aDlRWgazRFNou40=,iv:6k2M/7auUOCHABpUA3lgMuQO3BLUJKyaJZZGwSy/cSk=,tag:HgztFBp7r/9CYMGlJeX4tg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
