apps:
    web:
        DATABASE_URL: ENC[AES256_GCM,data:jyHECprXK2sC1KWXSGTF3Cm9cidNQjtc6Xx/nf+8cPYPukCjAEiuWa5ADCbMMREniJIo0ITWQCgFsLz3J+CmsfCHy0pId+8=,iv:YWbai8sGPEqUei4/mPxgKvjXNhM5eVk6x2YIH2Joo+0=,tag:TlwpUrzFixCTSXyo5LKOMQ==,type:str]
        BETTER_AUTH_URL: ENC[AES256_GCM,data:hL6bhU/7MVvUABAhZkESXHRcTRgW,iv:QBFMTivLtbRTekkEfk65VuAI8I/lkIslCr87VMAn0Gc=,tag:KIgPbrWT0JvjcpzmfPzLEw==,type:str]
        BETTER_AUTH_SECRET: ENC[AES256_GCM,data:j246aDeBflgn8bwx3sojkV4F4AXgGNYHYJUP1B0rFrKmy8mPf7Xxd/lNZW4OdtCnJFhIiVLZ+vNeaAe03Jkbug==,iv:BcrgqwUayoIzmstldUWRyuf3Caq1m5a4Q63kEA0JXkM=,tag:vPc5zlqMstlNOD3bv0p7qQ==,type:str]
        GITHUB_CLIENT_ID: ENC[AES256_GCM,data:aAUWx702TLFDmiyim1Oyh0RBDRuBeZzKdzDOFv+tSY8JWgAs,iv:cfiiL42YwOyjtg8lyrnpOtbVDPyS27lcEmCvNYhDJHg=,tag:I6KfJ0jMdKAyu+EOs2DSsQ==,type:str]
        GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:cBqYmpg23wP89PLW3IEdkjd9W3z9MO4KBsJ/LgrGbuLy9ZRq1KqY2w==,iv:3gHUaRt7yv5IhEncJwFZjTrXbIbAq3PBRNLS2bHEF0E=,tag:sJskv8vRT90wDz4DziGG4A==,type:str]
        GITHUB_ALLOWED_LOGIN: ENC[AES256_GCM,data:YJowNaaAbtlZWw31Pg==,iv:8FotkJWk0aH76pa/vy7+fFrlM3f3MXlds17lpWY4Tjo=,tag:tE4DiNVkqFHp7UUF8KmQZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVEExUlBqbHRERHlIeUc4
            ZFg4MFFlUVAyNEFaOHV0Y1F4bmtsaFFjUlJFCjhYbWZZaUFMaFJMK08yQTBnVjdm
            Q1d6d3ZBa21nWHZWK2NHYlQrUWUwOUUKLS0tIE1taUZtYmpvcTRjcVFJOUZ3WGNK
            QkNSU0xhSERpcjlYdTBtMWdzVi9SWG8KcNkVRFSplL5LA1GnllbdkozThNvo3V42
            wIZiP5DyeXpPdADn8dWkB7SFq1Jj7Ef61U9mRgstdd90qmZgy+Wv0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gxzu2f027zu227f4wyf4jh5sw0w495482qfzv5flmfyjvgzxm3ys8p9muz
    lastmodified: "2026-07-22T17:25:31Z"
    mac: ENC[AES256_GCM,data:p+U9+RIGDPiUO7BjoieH32y+xSy4ue3nw7pll3w+vTRt1qFyICi/QoJjQSt00DJQUTUF4UMt0vP3ZtajmLl+BxAZdfFfZlX3yRoQrKZ6BKL9rSzTYO2sWK2GaFh4Rp3mhUKLC+gYPZrBPATKhw2SIjb2tb0GE5Clf4wBcVlvGi8=,iv:RodFVL7pelIRu06T2SthXfZKrC5oEWadAr7e3UJ0aR0=,tag:fw2CJe3hgLfkjkvXeYX6qA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
